### PR TITLE
Heavybox 18.04 support

### PR DESCRIPTION
**Pull request by giorgiosironi**
Many states failing:

- [x] `git-lfs` hardcoding `trusty`
- [x] `redis` needing a new configuration file
- [x] `mysql-server` needing a new configuration file
- [ ] `newrelic-infrastructure` not supporting 18.04 yet
- [x] `openjdk7-jre` is not present so should be deprecated for 18.04
- [x] `php-ppa` needs to be switched to native packages or a new PPA?
- [x] `syslog-ng` has some error on startup
- [x] various `xenial` or `16.04` hardcodings
- [ ] [wontfix] `gearman` won't work on `16.04`
- [x] `crm` won't work with PHP 7.2

### CODE REVIEW

**Comment by giorgiosironi** [comment]
New Relic doesn't support 18.04 yet, but "they have it planned in their Jira":
https://discuss.newrelic.com/t/feature-idea-infrastructure-agent-should-run-on-ubuntu-18-04-lts/55587/12

**Comment by giorgiosironi** [comment]
The remaining 16.04 error is 
```
    heavybox--vagrant: [INFO    ] Executing command 'test -e /etc/apt/sources.list.d/ondrej-php-trusty.list || test -e /etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.lis
t' in directory '/root'
    heavybox--vagrant: [INFO    ] Executing command ['apt-add-repository', '-y', 'ppa:ondrej/pkg-gearman'] in directory '/root'
    heavybox--vagrant: [ERROR   ] Command '['apt-add-repository', '-y', 'ppa:ondrej/pkg-gearman']' failed with return code: 1
    heavybox--vagrant: [ERROR   ] stdout: 'ascii' codec can't decode byte 0xc5 in position 92: ordinal not in range(128)
    heavybox--vagrant: [ERROR   ] stderr: gpg: keyring `/tmp/tmp9ohqd7sj/secring.gpg' created
    heavybox--vagrant: gpg: keyring `/tmp/tmp9ohqd7sj/pubring.gpg' created
    heavybox--vagrant: gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
    heavybox--vagrant: gpg: /tmp/tmp9ohqd7sj/trustdb.gpg: trustdb created
    heavybox--vagrant: gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported
    heavybox--vagrant: gpg: Total number processed: 1
    heavybox--vagrant: gpg:               imported: 1  (RSA: 1)
    heavybox--vagrant: [ERROR   ] retcode: 1
    heavybox--vagrant: [ERROR   ] Failed to configure repo 'php-ppa-gearman': Unable to add PPA 'ondrej/pkg-gearman'. '['apt-add-repository', '-y', 'ppa:ondrej/pkg-gearman
']' exited with status 1: 'gpg: keyring `/tmp/tmp9ohqd7sj/secring.gpg' created
```
I can't reproduce it, and `search` is on 14.04 and the only project to use it. Going to skip `gearman.sls` on 16.04 leaving it on 18.04 where it works without the need for PPAs.

**Comment by lsh-0** [comment]
I can't reproduce the above either (in Vagrant 16.04). 

I'm getting lots of 'temporary name resolution errors' on Vagrant 18.04 when the box can't connect to git, or the ubuntu mirror, or salt - hopefully it's just a vagrant/local thing - but I can build heavybox in both now, so I'll take a look at your remaining checkboxes tomorrow

**Comment by lsh-0** [comment]
I'm going through the states that hardcode mentions of specific distributions and seeing if they can be tweaked

**Comment by lsh-0** [comment]
my work is happening here: PR: https://github.com/elifesciences/builder-base-formula/pull/174

I'll merge it into this branch when it's green

**Comment by lsh-0** [comment]
> crm won't work with PHP 7.2

I think it might be related to `mcrypt` going away in 7.2 and being replaced with libsodium. There is also Drupal 7.59 that doesn't support 7.2 (but [7.60 apparently will](https://www.drupal.org/project/drupal/issues/2947772)).

Couldn't find any official word from Civi about 7.2 support

**Comment by lsh-0** [comment]
I essentially visited every mention of:
* 14.04
* 16.04
* 18.04
* trusty
* xenial
* bionic

and reviewed the logic. A good number needed refactoring so 18.04 wasn't being excluded, or 14.04 logic being reintroduced because of the way I had previously don't the if-elses.

I also:
* added the apache states into heavybox and disabled the service to get some coverage for `crm` that way.
* removed the collectd state file, config file and pillar data
* replaced any dependencies on the `java.sls` state file with `java8.sls` (we had arges, jats4r-validator and observer)
* removed some dummy 'ppa' states leftover from 14.04 rather than perpetuate them onwards

I can't guarantee everything in builder-base has been reviewed.

**Comment by lsh-0** [comment]
I'll merge this tomorrow

**Pull request merged**
