### PR TITLE
Fix: newrelic_python further restricted

### PR DESCRIPTION
**Pull request by lsh-0**
* `newrelic_python.sls` states only available if newrelic enabled AND newrelic_python configuration available.

we had a highstate failure in `elife-dashboard--prod` with:

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:elife.newrelic-python' failed: Jinja variable 'dict object' has no attribute 'newrelic_python'
```

because the `elife.newrelic_python` state had been included in the `top.sls` file but no `pillar.elife.newrelic_python` configuration made available.

I know it says *right at the top of the file* that the state file cannot be included without also specifying [...] but this would change it from a hard failure with an esoteric message to a failed state with a descriptive error message.

Not sure which approach is better, feel free to close if you prefer the original way

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Retrying build to see if we can keep it green thanks to https://github.com/elifesciences/heavybox-formula/pull/10

**Comment by giorgiosironi** [comment]
The answer is: everything breaks, of course.

**Comment by giorgiosironi** [comment]
Back to :green_apple:

**Comment by lsh-0** [comment]
huh. had forgotten all about this

**Pull request merged**
