### PR TITLE
Added platform.sh Enterprise platform public key for git-pushing to it

### PR DESCRIPTION
**Pull request by giorgiosironi**
```
$ ssh-keyscan -t ssh-rsa -H git.ent.platform.sh > key.pub && ssh-keygen -l -f key.pub
2048 8f:1d:0e:16:ec:00:dd:b2:ad:02:2c:d6:fa:ef:46:91 |1|NaIe0MCS+Ew2+qgkP8gNRF9Iz0I=|Qst2/OtXTmamuFnf8eV+ZPZAeFM= (RSA)
```

### CODE REVIEW

**Comment by lsh-0** [comment]
this doesn't really have a place in `builder-base-formula` - I think it's too elife specific.

that begs the question "where do we put it?"

**Comment by lsh-0** [comment]
perhaps we turn it into configuration, a list of servers we need to fingerprint in pillar

**Comment by giorgiosironi** [comment]
True, should be a pillar configuration.

**Comment by giorgiosironi** [comment]
Goodbye platform.sh

**Pull request closed without merging**
