### PR TITLE
Fix: docker.sls, pins version of docker-ce on Trusty (14.04) systems

### PR DESCRIPTION
**Pull request by lsh-0**
temporary until proper support for 3.3 kernel is released

### CODE REVIEW

**Comment by lsh-0** [comment]
unrelated error caused the state to not even be reached:
```
[2019-03-01T06:29:48.621Z] [3.85.108.38] out: ----------
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:           ID: php
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:     Function: pkg.installed
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:       Result: False
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:      Comment: Problem encountered installing package(s). Additional info follows:
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:               
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:               errors:
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:                   - E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:                     E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:      Started: 06:25:01.888655
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:     Duration: 144.109 ms
[2019-03-01T06:29:48.621Z] [3.85.108.38] out:      Changes:   
[2019-03-01T06:29:48.621Z] [3.85.108.38] out: ----------
```

(race condition?)

and then just heaps of cascading failures. Will give build a kick

**Comment by lsh-0** [comment]
better result this time with just two failures in the base state:

```
[2019-03-01T06:52:21.536Z] [100.24.37.89] out: ----------
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:           ID: goaws
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:     Function: cmd.run
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:         Name: rm -f ../goaws-docker-compose.yml
[2019-03-01T06:52:21.536Z] [100.24.37.89] out: (docker stop goaws && docker rm goaws) || true
[2019-03-01T06:52:21.536Z] [100.24.37.89] out: /usr/local/bin/docker-compose -f docker-compose.yml up --force-recreate -d
[2019-03-01T06:52:21.536Z] [100.24.37.89] out: 
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:       Result: False
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:      Comment: Command "rm -f ../goaws-docker-compose.yml
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:               (docker stop goaws && docker rm goaws) || true
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:               /usr/local/bin/docker-compose -f docker-compose.yml up --force-recreate -d
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:               " run
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:      Started: 06:47:26.370168
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:     Duration: 1841.498 ms
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:      Changes:   
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:               ----------
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:               pid:
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:                   27394
[2019-03-01T06:52:21.536Z] [100.24.37.89] out:               retcode:
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   1
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:               stderr:
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   Error response from daemon: No such container: goaws
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   Pulling goaws (elifesciences/goaws:1.0.1)...
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   Creating goaws ... 
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   ?[1A?[2K
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   Creating goaws ... ?[31merror?[0m
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   ?[1B
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   ERROR: for goaws  Cannot start service goaws: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   ERROR: for goaws  Cannot start service goaws: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   Encountered errors while bringing up the project.
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:               stdout:
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   1.0.1: Pulling from elifesciences/goaws
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   Digest: sha256:e7849640fc1996fd030ea8e9e0105cfa63fa985361cfb7cc6d2561a658428b62
[2019-03-01T06:52:21.537Z] [100.24.37.89] out:                   Status: Downloaded newer image for elifesciences/goaws:1.0.1
[2019-03-01T06:52:21.537Z] [100.24.37.89] out: ----------

[2019-03-01T06:52:21.880Z] [100.24.37.89] out:           ID: docker-compose-sftp-up
[2019-03-01T06:52:21.880Z] [100.24.37.89] out:     Function: cmd.run
[2019-03-01T06:52:21.880Z] [100.24.37.89] out:         Name: /usr/local/bin/docker-compose -f docker-compose.yml up --force-recreate -d
[2019-03-01T06:52:21.880Z] [100.24.37.89] out:       Result: False
[2019-03-01T06:52:21.880Z] [100.24.37.89] out:      Comment: Command "/usr/local/bin/docker-compose -f docker-compose.yml up --force-recreate -d" run
[2019-03-01T06:52:21.880Z] [100.24.37.89] out:      Started: 06:50:57.174594
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:     Duration: 3257.074 ms
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:      Changes:   
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:               ----------
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:               pid:
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   11114
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:               retcode:
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   1
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:               stderr:
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   Pulling sftp (elifesciences/sftp:20190110)...
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   Creating sftp ... 
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   ?[1A?[2K
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   Creating sftp ... ?[31merror?[0m
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   ?[1B
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   ERROR: for sftp  Cannot start service sftp: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   ERROR: for sftp  Cannot start service sftp: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 23\"": unknown
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   Encountered errors while bringing up the project.
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:               stdout:
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   20190110: Pulling from elifesciences/sftp
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   Digest: sha256:559b252e516eae1ea8695807d22cba029a18dbf1671d330db10b067c8ba46d18
[2019-03-01T06:52:21.881Z] [100.24.37.89] out:                   Status: Downloaded newer image for elifesciences/sftp:20190110
```

**Comment by giorgiosironi** [comment]
I think we cannot fix `pr-base` as that uses the `master` of this repository only. So from the checks I consider this build green.

**Comment by giorgiosironi** [comment]
> (race condition?)

Yes, some cron running while `apt-get` is doing its job.

**Comment by giorgiosironi** [comment]
`fresh`:
```
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:           ID: docker-packages
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:     Function: pkg.installed
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:       Result: True
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:      Comment: 1 targeted package was installed/updated.
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:      Started: 06:46:42.677557
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:     Duration: 16272.443 ms
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:      Changes:   
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:               ----------
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:               aufs-tools:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   ----------
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   new:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                       1:3.2+20130722-1.1
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   old:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:               cgroup-lite:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   ----------
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   new:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                       1.9
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   old:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:               docker-ce:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   ----------
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   new:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                       18.06.1~ce~3-0~ubuntu
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   old:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:               libltdl7:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   ----------
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   new:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                       2.4.2-1.7ubuntu1
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   old:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:               libsystemd-journal0:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   ----------
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   new:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                       204-5ubuntu20.29
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   old:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:               pigz:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   ----------
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   new:
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                       2.3-2
[2019-03-01T06:52:17.546Z] [3.93.68.233] out:                   old:
```
`fresh` on 16.04:
```
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:           ID: docker-packages
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:     Function: pkg.installed
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:       Result: True
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:      Comment: The following packages were installed/updated: docker-ce
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:      Started: 06:46:15.983376
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:     Duration: 19577.257 ms
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:      Changes:   
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:               ----------
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:               aufs-tools:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   ----------
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   new:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                       1:3.2+20130722-1.1ubuntu1
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   old:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:               cgroupfs-mount:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   ----------
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   new:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                       1.2
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   old:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:               containerd.io:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   ----------
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   new:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                       1.2.4-1
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   old:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:               docker-ce:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   ----------
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   new:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                       5:18.09.3~3-0~ubuntu-xenial
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   old:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:               docker-ce-cli:
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   ----------
[2019-03-01T06:49:48.351Z] [3.91.60.120] out:                   new:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                       5:18.09.3~3-0~ubuntu-xenial
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   old:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:               libltdl7:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   ----------
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   new:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                       2.4.6-0.1
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   old:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:               libseccomp2:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   ----------
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   new:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                       2.3.1-2.1ubuntu2~16.04.1
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   old:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                       2.2.3-3ubuntu3
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:               pigz:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   ----------
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   new:
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                       2.3.1-2
[2019-03-01T06:49:48.352Z] [3.91.60.120] out:                   old:
```

**Pull request merged**
