### PR TITLE
Add coveralls placeholder

### PR DESCRIPTION
**Pull request by seanwiseman**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
It would make sense to have the `elife/coveralls.sls` state using this in the same PR too.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/elife-libraries-formula/blob/master/salt/elife-libraries/init.sls#L166-L174 needs to be copied and adapted into a new file `elife/coveralls.sls`.

**Comment by giorgiosironi** [comment]
Then, `.coveralls` could be added at https://github.com/elifesciences/builder-base-formula/blob/master/elife/init.sls#L12

**Comment by giorgiosironi** [comment]
Then (3rd step), add configuration to https://github.com/elifesciences/profiles-formula/blob/master/salt/pillar/profiles.sls#L31 and you should start seeing it in the `vagrant provision` result.

**Comment by giorgiosironi** [comment]
The build is complaining because EC2 instances use `builder-private`, after adding the configuration there it should become green.

**Comment by seanwiseman** [comment]
Looking good now @giorgiosironi ?

**Pull request merged**
