### PR TITLE
Feature: uwsgi.sls, adds ability to disable newrelic for specific uwsgi services

### PR DESCRIPTION
**Pull request by lsh-0**
came about because I forgot to update bot-lax in the lax formula and bot-lax doesn't appear to support newrelic (yet). it probably should. another ticket perhaps.

edit: it also adds the `--socket` and `--log-to` params for newrelic-enabled services that I appear to have left out of previous commits

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Wait, `bot-lax-adaptor` should already support New Relic:
https://github.com/elifesciences/bot-lax-adaptor/blob/develop/requirements.txt#L15
Though it is used in the background process rather than on the web side:
https://github.com/elifesciences/bot-lax-adaptor/blob/58318286ab8d07d206abe34b313f63ce51117d31/src/adaptor.py#L309-L315

**Comment by giorgiosironi** [comment]
The feature would be ok (pending green tests), but I'd like to understand the failure more.

**Comment by lsh-0** [comment]
huh. yeah, I'll take a look. for posterity:

```
[2019-03-20T05:05:19.318Z] INFO - botocore.vendored.requests.packages.urllib3.connectionpool - Starting new HTTPS connection (2): elife-builder.s3.amazonaws.com
[2019-03-20T05:05:19.568Z] [localhost] local: ssh -o "StrictHostKeyChecking no" ubuntu@184.73.15.149 "exit"
[2019-03-20T05:05:19.568Z] Traceback (most recent call last):
[2019-03-20T05:05:19.568Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/main.py", line 757, in main
[2019-03-20T05:05:19.568Z]     *args, **kwargs
[2019-03-20T05:05:19.568Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
[2019-03-20T05:05:19.568Z]     results['<local-only>'] = task.run(*args, **new_kwargs)
[2019-03-20T05:05:19.568Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
[2019-03-20T05:05:19.568Z]     return self.wrapped(*args, **kwargs)
[2019-03-20T05:05:19.568Z]   File "/ext/srv/builder/src/decorators.py", line 58, in wrap2
[2019-03-20T05:05:19.568Z]     return func(pname, *args, **kwargs)
[2019-03-20T05:05:19.568Z]   File "/ext/srv/builder/src/masterless.py", line 22, in wrapper
[2019-03-20T05:05:19.568Z]     return fn(*args, **kwargs)
[2019-03-20T05:05:19.568Z]   File "/ext/srv/builder/src/masterless.py", line 89, in launch
[2019-03-20T05:05:19.568Z]     ensure(pdata['aws-alt'], "project has no alternate configurations")
[2019-03-20T05:05:19.568Z] KeyError: 'aws-alt'
```

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder/commit/434f3ba95a6ffd42e4dac0a67bd865ba53299284 fixed this yesterday.

**Pull request merged**
