### PR TITLE
Bugfix gearman ppa

### PR DESCRIPTION
**Pull request by lsh-0**
this should fix it for both trusty and xenial

### CODE REVIEW

**Comment by lsh-0** [comment]
ah! I can see Alfred at work now. cool. I'll merge it if it passes

**Comment by lsh-0** [comment]
eh. failed. testing a fresh install manually

**Comment by lsh-0** [comment]
can't replicate Alfred's problem on a fresh install, my fix works.

@giorgiosironi could you please merge this at your convenience.

**Comment by giorgiosironi** [comment]
I don't know how this works: I thought this kind of file checking is executed at YAML rendering time. If that was it, the files shouldn't be there as the other Salt state adding the `ondrej` repositories has not been executed yet.

But since it works experimentally, let's merge.

**Comment by giorgiosironi** [comment]
It seems sometimes we want to run a build from scratch on a branch rather than building with the existing formula and then switch to the new commit. An idea for the future, if `builder` allows it.

**Comment by lsh-0** [comment]
> I don't know how this works: I thought this kind of file checking is executed at YAML rendering time.

that's a good point. it was a check that started off as one thing, then became another, then two checks and suddenly you have something that should be done at runtime rather than compiletime. If it causes problems, we can add an elaborate `onlyif`

**Pull request merged**
