### PR TITLE
Extract first nginx macro

### PR DESCRIPTION
**Pull request by giorgiosironi**
Black magic to extract [this other piece of black magic](https://github.com/elifesciences/lax-formula/blob/master/salt/lax/config/etc-nginx-sitesavailable-lax.conf#L18-L25) and make it reusable from other formulas (in this case `journal-cms`).

[Macros official documentation](https://docs.saltstack.com/en/2017.7/topics/jinja/index.html#macros) is available. The backlinked PR on `lax-formula` shows how to use this.

### CODE REVIEW

**Comment by lsh-0** [comment]
I've never seen any of this before. The stuff in the lax formula has no explanation and I don't remember reviewing it. I have nfi what you are doing.

**Comment by giorgiosironi** [comment]
[It goes back to 2017](https://github.com/elifesciences/lax-formula/pull/12). Longer explanation follows.

This is how an article page gets its (private) data from `lax`:
```
journal -> api-gateway -> lax
```
In particular, the HTTP headers are:
```
journal --Authorization:journalapikey--> api-gateway --X-Consumer-Groups:view-unpublished-articles--> lax
```
However, if `lax` is publicly accessible, someone could pass `X-Consumer-Groups` directly. So instead we add authentication between `api-gateway` and `lax`:
```
journal --Authorization:journalapikey--> api-gateway --X-Consumer-Groups:view-unpublished-articles,Authorization:apigatewayandlaxsharedsecret--> lax
```
This nginx configuration kills `X-Consumer-Groups` if `apigatewayandlaxsharedsecret` is not there, filtering it out.

Lately `journal-cms` has got the same problem: being accessed through `api-gateway` but also being exposed directly. So this extraction will allow it to use the same pattern without copying and pasting. I'll add some comments as this is pretty obscure, I agree.

**Comment by lsh-0** [comment]
ah, there I am giving my tick of approval. I didn't find this yesterday when going through that file's commit history.

That PR has a good explanation:

> This method replaces the need to check the ip address of the caller.
> Nginx strips the X-Consumer-Groups header, letting it through only if the caller satisfied the basic authentication. Only the api-gateway should know this secret.

**Comment by giorgiosironi** [comment]
(related issue is in the Todo column, will get back to this when picking it up)

**Pull request merged**
