### PR TITLE
added autoremove state.

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
run inside Vagrant, I got this (slightly troubling) output:

```
----------
          ID: autoremove-orphans
    Function: cmd.run
        Name: apt-get autoremove -y
      Result: True
     Comment: Command "apt-get autoremove -y" run
     Started: 03:28:18.867116
    Duration: 52157.362 ms
     Changes:   
              ----------
              pid:
                  2513
              retcode:
                  0
              stderr:
                  Examining /etc/kernel/prerm.d.
                  run-parts: executing /etc/kernel/prerm.d/dkms 3.13.0-100-generic /boot/vmlinuz-3.13.0-100-generic
                  dkms: removing: virtualbox-guest 4.3.36 (3.13.0-100-generic) (x86_64)
                  Examining /etc/kernel/postrm.d .
                  run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.13.0-100-generic /boot/vmlinuz-3.13.0-100-generic
                  update-initramfs: Deleting /boot/initrd.img-3.13.0-100-generic
                  run-parts: executing /etc/kernel/postrm.d/zz-update-grub 3.13.0-100-generic /boot/vmlinuz-3.13.0-100-generic
                  Generating grub configuration file ...
                  Found linux image: /boot/vmlinuz-3.13.0-112-generic
                  Found initrd image: /boot/initrd.img-3.13.0-112-generic
                  Found linux image: /boot/vmlinuz-3.13.0-107-generic
                  Found initrd image: /boot/initrd.img-3.13.0-107-generic
                  Found linux image: /boot/vmlinuz-3.13.0-101-generic
                  Found initrd image: /boot/initrd.img-3.13.0-101-generic
                  Found linux image: /boot/vmlinuz-3.13.0-83-generic
                  Found initrd image: /boot/initrd.img-3.13.0-83-generic
                  done
                  Examining /etc/kernel/prerm.d.
                  run-parts: executing /etc/kernel/prerm.d/dkms 3.13.0-101-generic /boot/vmlinuz-3.13.0-101-generic
                  dkms: removing: virtualbox-guest 4.3.36 (3.13.0-101-generic) (x86_64)
                  Examining /etc/kernel/postrm.d .
                  run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.13.0-101-generic /boot/vmlinuz-3.13.0-101-generic
                  update-initramfs: Deleting /boot/initrd.img-3.13.0-101-generic
                  run-parts: executing /etc/kernel/postrm.d/zz-update-grub 3.13.0-101-generic /boot/vmlinuz-3.13.0-101-generic
                  Generating grub configuration file ...
                  Found linux image: /boot/vmlinuz-3.13.0-112-generic
                  Found initrd image: /boot/initrd.img-3.13.0-112-generic
                  Found linux image: /boot/vmlinuz-3.13.0-107-generic
                  Found initrd image: /boot/initrd.img-3.13.0-107-generic
                  Found linux image: /boot/vmlinuz-3.13.0-83-generic
                  Found initrd image: /boot/initrd.img-3.13.0-83-generic
                  done
                  Examining /etc/kernel/prerm.d.
                  run-parts: executing /etc/kernel/prerm.d/dkms 3.13.0-83-generic /boot/vmlinuz-3.13.0-83-generic
                  dkms: removing: virtualbox-guest 4.3.36 (3.13.0-83-generic) (x86_64)
                  Examining /etc/kernel/postrm.d .
                  run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.13.0-83-generic /boot/vmlinuz-3.13.0-83-generic
                  update-initramfs: Deleting /boot/initrd.img-3.13.0-83-generic
                  run-parts: executing /etc/kernel/postrm.d/zz-update-grub 3.13.0-83-generic /boot/vmlinuz-3.13.0-83-generic
                  Generating grub configuration file ...
                  Found linux image: /boot/vmlinuz-3.13.0-112-generic
                  Found initrd image: /boot/initrd.img-3.13.0-112-generic
                  Found linux image: /boot/vmlinuz-3.13.0-107-generic
                  Found initrd image: /boot/initrd.img-3.13.0-107-generic
                  done
              stdout:
                  Reading package lists...
                  Building dependency tree...
                  Reading state information...
                  The following packages will be REMOVED:
                    linux-headers-3.13.0-100 linux-headers-3.13.0-100-generic
                    linux-headers-3.13.0-101 linux-headers-3.13.0-101-generic
                    linux-headers-3.13.0-83 linux-headers-3.13.0-83-generic
                    linux-image-3.13.0-100-generic linux-image-3.13.0-101-generic
                    linux-image-3.13.0-83-generic
                  0 upgraded, 0 newly installed, 9 to remove and 88 not upgraded.
                  After this operation, 360 MB disk space will be freed.
                  (Reading database ... 174675 files and directories currently installed.)
                  Removing linux-headers-3.13.0-100-generic (3.13.0-100.147) ...
                  Removing linux-headers-3.13.0-100 (3.13.0-100.147) ...
                  Removing linux-headers-3.13.0-101-generic (3.13.0-101.148) ...
                  Removing linux-headers-3.13.0-101 (3.13.0-101.148) ...
                  Removing linux-headers-3.13.0-83-generic (3.13.0-83.127) ...
                  Removing linux-headers-3.13.0-83 (3.13.0-83.127) ...
                  Removing linux-image-3.13.0-100-generic (3.13.0-100.147) ...
                  
                  -------- Uninstall Beginning --------
                  Module:  virtualbox-guest
                  Version: 4.3.36
                  Kernel:  3.13.0-100-generic (x86_64)
                  -------------------------------------
                  
                  Status: Before uninstall, this module version was ACTIVE on this kernel.
                  
                  vboxguest.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-100-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  
                  vboxsf.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-100-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  
                  vboxvideo.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-100-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  depmod.....
                  
                  DKMS: uninstall completed.
                  Removing linux-image-3.13.0-101-generic (3.13.0-101.148) ...
                  
                  -------- Uninstall Beginning --------
                  Module:  virtualbox-guest
                  Version: 4.3.36
                  Kernel:  3.13.0-101-generic (x86_64)
                  -------------------------------------
                  
                  Status: Before uninstall, this module version was ACTIVE on this kernel.
                  
                  vboxguest.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-101-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  
                  vboxsf.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-101-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  
                  vboxvideo.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-101-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  depmod.....
                  
                  DKMS: uninstall completed.
                  Removing linux-image-3.13.0-83-generic (3.13.0-83.127) ...
                  
                  -------- Uninstall Beginning --------
                  Module:  virtualbox-guest
                  Version: 4.3.36
                  Kernel:  3.13.0-83-generic (x86_64)
                  -------------------------------------
                  
                  Status: Before uninstall, this module version was ACTIVE on this kernel.
                  
                  vboxguest.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-83-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  
                  vboxsf.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-83-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  
                  vboxvideo.ko:
                   - Uninstallation
                     - Deleting from: /lib/modules/3.13.0-83-generic/updates/dkms/
                   - Original module
                     - No original module was found for this module on this kernel.
                     - Use the dkms install command to reinstall any previous module version.
                  
                  depmod....
                  
                  DKMS: uninstall completed.
```

but after stopping the vagrant instance and starting it again, it worked fine.

**Comment by lsh-0** [comment]
please merge if you're happy with it.

**Comment by lsh-0** [comment]
also snuck in a change to the backup strategy that seems reasonable.

**Comment by giorgiosironi** [comment]
I think it's right to delegate this job to apt, if `autoremove` doesn't work we have to make that command work rather than inventing our own method.

**Pull request merged**
