### PR TITLE
Expand support for sidecars for mailcatcher

### PR DESCRIPTION
**Pull request by giorgiosironi**
- Make `main` optional
- Support `ports` not just `port`
- Improve formatting of `docker-compose.yml` avoiding empty lines

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Next `pr-fresh` should fail, then I'll debug manually on a masterless instance.

**Comment by giorgiosironi** [comment]
Almost solved this but `oracle-java-installer` broke again:

```
--2018-07-31 10:00:18--  http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-linux-x64.tar.gz?AuthParam=1533031338_1fd50222e55c741d985a9d7d25c45d69
HTTP request sent, awaiting response... 404 Not Found
2018-07-31 10:00:20 ERROR 404: Not Found.
```

**Comment by giorgiosironi** [comment]
`pr-base` is broken as expected, but `pr-fresh` is finally green.

**Comment by lsh-0** [comment]
> Almost solved this but oracle-java8-installer broke again
perhaps we ought to host this one ourselves

**Pull request merged**
