### PR TITLE
feat: ssl serve complete cert

### PR DESCRIPTION
**Pull request by lsh-0**
nginx, fixes an ssl stapling issue not present 14.04 but present 16.04
creates a third file that is the certificate + gandi intermediate certificate

### CODE REVIEW

**Comment by lsh-0** [comment]
argh - I was still testing. also, it's broken

**Comment by giorgiosironi** [comment]
No worries, just found the syntax problem, will be part of the testing and we can revert if needed.

**Comment by lsh-0** [comment]
fixed syntax error and testing here: certfix--lax.elifesciences.org

**Comment by giorgiosironi** [comment]
The latest master fixed elife-xpub--* stacks: https://ci--alfred.elifesciences.org/job/test-elife-xpub/25/consoleFull

**Comment by lsh-0** [comment]
(this is a helpful little tool btw: https://www.digicert.com/help/)

**Comment by lsh-0** [comment]
yeah the fix works fine on 14.04 - this shouldn't break existing systems

**Comment by giorgiosironi** [comment]
The `elife-xpub--demo` stacks also passes digicert.com tests

**Pull request merged**
