### PR TITLE
Docker 18.09.3 upgrade and pin

### PR DESCRIPTION
**Pull request by giorgiosironi**
Includes https://github.com/moby/moby/issues/38249#issuecomment-474795342 which has been afflicting `elife-xpub`.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Such a simple thing, so difficult to do. @lsh-0 can you help out with finding the magic formula on how to specify the version?
From a 16.04 instance:
```
elife@end2end--xpub:~$ sudo apt-cache madison docker-ce | grep 18.09
 docker-ce | 5:18.09.3~3-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
 docker-ce | 5:18.09.2~3-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
 docker-ce | 5:18.09.1~3-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
 docker-ce | 5:18.09.0~3-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages
```

**Comment by lsh-0** [comment]
I'll take a look, sure

**Comment by lsh-0** [comment]
I can replicate this locally on a vagrant vm running heavybox + 18.04

**Comment by giorgiosironi** [comment]
Moved to https://github.com/elifesciences/builder-base-formula/pull/215

**Pull request closed without merging**
