### PR TITLE
pins the stable version of ubr

### PR DESCRIPTION
**Pull request by lsh-0**
Hi @giorgiosironi ,

I've made some big changes to ubr that never made it into master. this PR is an effort to ensure the version of UBR installed on the hosts is the stable one while we add UBR to the testing environment.

If this is your preferred way of pinning, please merge.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
`git.detached`, nice to know. Pointing out with this change we pin the version on all stacks at the same time. I think it's the right level of granularity (definitely don't need to have different versions on different projects).

**Comment by lsh-0** [comment]
yeah - it also ensure we can roll back if I totally break something - there *are* a lot of changes in the develop branch.

**Comment by giorgiosironi** [comment]
We run into this Salt bug https://github.com/saltstack/salt/pull/34463
which should be fixed in `2016.3.2` (we use `2016.3.4` in theory), but `elife-bot--ci` still has `2016.3.1`.

**Comment by giorgiosironi** [comment]
(error: https://ci--alfred.elifesciences.org/job/pull-requests-projects/job/elife-bot/job/PR-378/2/console)

**Comment by giorgiosironi** [comment]
The problem is that `bldr update` runs the `scripts/bootstrap.sh` that upgrades basic infrastructure such as Python and Salt. `bldr switch_revision_update_instance` (used in Alfred builds) instead changes the build vars and runs `scripts/highstate.sh` only. Should it also run `scripts/bootstrap.sh`?

**Comment by giorgiosironi** [comment]
Captured at https://github.com/elifesciences/builder/pull/96

**Pull request merged**
