### PR TITLE
Feature: gearman, disables installation of upstart script in non-14.04 instances

### PR DESCRIPTION
**Pull request by lsh-0**
it's not dong any harm right now, I'm just trying to clean up the gearman configuration in `search`

### CODE REVIEW

**Comment by giorgiosironi** [comment]
What do we do with PHP in 14.04? Even when we will have ported away all projects, the state will continue to fail there and breaking the full build for these pull requests.

**Comment by lsh-0** [comment]
I was thinking about that today actually. I didn't have any nice solutions, unfortunately. I figured we put up with it until all projects are ported away and then purge the 14.04 bits. And the php ppa bits.

**Comment by lsh-0** [comment]
or we shift the default AMI to 16.04 for everything?

**Comment by giorgiosironi** [comment]
On the 14.04 PHP status:
https://github.com/elifesciences/heavybox-formula/pull/10

**Pull request merged**
